sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t jvck10/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jvck10/docker-react npm start test