sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t jvck10/docker-react -f Dockerfile.dev .

script:
    - docker -e CI=true run jvck10/docker-react npm run test